name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up JDK 17 (Required for building Kotlin/Android projects)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # Fix permissions on gradlew
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Run Gradle build (to compile your project)
      - name: Build the project
        run: ./gradlew build

      # Run unit tests (you already have tests in your project)
      - name: Run unit tests
        run: ./gradlew test

      # Upload the APK (or AAB) build artifact
      - name: Upload APK or AAB
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            app/build/outputs/apk/debug/
            app/build/outputs/apk/release/
            app/build/outputs/bundle/release/

