name: Build and Test Android App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      # Set up Android SDK
      - name: Set up Android SDK
        uses: reactivecircus/android-emulator-action@v2
        with:
          api-level: 30
          arch: x86_64
          target: google_apis
          force-avd-creation: true
          emulator-options: -no-window -gpu off

      # Build the app
      - name: Build Debug APK
        run: ./gradlew assembleDebug

      # Run tests (Optional: If you have automated tests)
      - name: Run tests
        run: ./gradlew testDebugUnitTest
